"""attachments

Revision ID: 0b4ae74dbb70
Revises: f6703a0bb868
Create Date: 2026-09-01 17:14:01.860586
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0b4ae74dbb70'
down_revision: str | None = 'f6703a0bb868'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['conversation_id'], ['genie.conversations.id'],
        name='fk_attachments_conversation_id', ondelete='CASCADE',
    ),
    sa.ForeignKeyConstraint(
        ['message_id'], ['genie.messages.id'],
        name='fk_attachments_message_id', ondelete='SET NULL',
    ),
    sa.ForeignKeyConstraint(
        ['user_id'], ['genie.users.id'],
        name='fk_attachments_user_id', ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    schema='genie'
    )
    op.create_index(op.f('ix_genie_attachments_conversation_id'), 'attachments', ['conversation_id'], unique=False, schema='genie')
    op.create_index(op.f('ix_genie_attachments_user_id'), 'attachments', ['user_id'], unique=False, schema='genie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genie_attachments_user_id'), table_name='attachments', schema='genie')
    op.drop_index(op.f('ix_genie_attachments_conversation_id'), table_name='attachments', schema='genie')
    op.drop_table('attachments', schema='genie')
    # ### end Alembic commands ###
