"""users, conversations, messages (genie schema)

Revision ID: 1c61bba11678
Revises: 
Create Date: 2026-08-29 16:04:15.671160
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1c61bba11678'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('token_budget', sa.BigInteger(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='genie'
    )
    op.create_index(op.f('ix_genie_users_clerk_id'), 'users', ['clerk_id'], unique=True, schema='genie')
    op.create_index(op.f('ix_genie_users_email'), 'users', ['email'], unique=True, schema='genie')
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['genie.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='genie'
    )
    op.create_index(op.f('ix_genie_conversations_user_id'), 'conversations', ['user_id'], unique=False, schema='genie')
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['genie.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['genie.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='genie'
    )
    op.create_index(op.f('ix_genie_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='genie')
    op.create_index(op.f('ix_genie_messages_user_id'), 'messages', ['user_id'], unique=False, schema='genie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genie_messages_user_id'), table_name='messages', schema='genie')
    op.drop_index(op.f('ix_genie_messages_conversation_id'), table_name='messages', schema='genie')
    op.drop_table('messages', schema='genie')
    op.drop_index(op.f('ix_genie_conversations_user_id'), table_name='conversations', schema='genie')
    op.drop_table('conversations', schema='genie')
    op.drop_index(op.f('ix_genie_users_email'), table_name='users', schema='genie')
    op.drop_index(op.f('ix_genie_users_clerk_id'), table_name='users', schema='genie')
    op.drop_table('users', schema='genie')
    # ### end Alembic commands ###
