"""conversation last_message_at + index

Revision ID: 34e9ccc89880
Revises: 1c61bba11678
Create Date: 2026-08-29 22:23:18.395995
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '34e9ccc89880'
down_revision: str | None = '1c61bba11678'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True), schema='genie')
    op.create_index('ix_conversations_user_recent', 'conversations', ['user_id', 'last_message_at'], unique=False, schema='genie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_user_recent', table_name='conversations', schema='genie')
    op.drop_column('conversations', 'last_message_at', schema='genie')
    # ### end Alembic commands ###
