"""projects

Revision ID: 84a8e112e61f
Revises: 34e9ccc89880
Create Date: 2026-08-29 22:46:57.631220
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '84a8e112e61f'
down_revision: str | None = '34e9ccc89880'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['genie.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='genie'
    )
    op.create_index(op.f('ix_genie_projects_user_id'), 'projects', ['user_id'], unique=False, schema='genie')
    op.add_column('conversations', sa.Column('project_id', sa.Uuid(), nullable=True), schema='genie')
    op.create_index(op.f('ix_genie_conversations_project_id'), 'conversations', ['project_id'], unique=False, schema='genie')
    op.create_foreign_key('fk_conversations_project_id', 'conversations', 'projects', ['project_id'], ['id'], source_schema='genie', referent_schema='genie', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversations_project_id', 'conversations', schema='genie', type_='foreignkey')
    op.drop_index(op.f('ix_genie_conversations_project_id'), table_name='conversations', schema='genie')
    op.drop_column('conversations', 'project_id', schema='genie')
    op.drop_index(op.f('ix_genie_projects_user_id'), table_name='projects', schema='genie')
    op.drop_table('projects', schema='genie')
    # ### end Alembic commands ###
