"""tasks

Revision ID: bed5223f2a47
Revises: 84a8e112e61f
Create Date: 2026-08-31 18:20:08.825679
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bed5223f2a47'
down_revision: str | None = '84a8e112e61f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_agent', sa.String(length=50), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['conversation_id'], ['genie.conversations.id'],
        name='fk_tasks_conversation_id', ondelete='SET NULL',
    ),
    sa.ForeignKeyConstraint(
        ['user_id'], ['genie.users.id'],
        name='fk_tasks_user_id', ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    schema='genie'
    )
    op.create_index(op.f('ix_genie_tasks_conversation_id'), 'tasks', ['conversation_id'], unique=False, schema='genie')
    op.create_index(op.f('ix_genie_tasks_user_id'), 'tasks', ['user_id'], unique=False, schema='genie')
    op.create_index('ix_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False, schema='genie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_status', table_name='tasks', schema='genie')
    op.drop_index(op.f('ix_genie_tasks_user_id'), table_name='tasks', schema='genie')
    op.drop_index(op.f('ix_genie_tasks_conversation_id'), table_name='tasks', schema='genie')
    op.drop_table('tasks', schema='genie')
    # ### end Alembic commands ###
