"""generated_files

Revision ID: e4d1c7a3a02d
Revises: b8e2f4a1c9d3
Create Date: 2026-09-05 00:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e4d1c7a3a02d'
down_revision: str | None = 'b8e2f4a1c9d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('s3_key', sa.String(length=600), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['conversation_id'], ['genie.conversations.id'],
        name='fk_generated_files_conversation_id', ondelete='CASCADE',
    ),
    sa.ForeignKeyConstraint(
        ['message_id'], ['genie.messages.id'],
        name='fk_generated_files_message_id', ondelete='SET NULL',
    ),
    sa.ForeignKeyConstraint(
        ['user_id'], ['genie.users.id'],
        name='fk_generated_files_user_id', ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    schema='genie'
    )
    op.create_index(op.f('ix_genie_generated_files_conversation_id'), 'generated_files', ['conversation_id'], unique=False, schema='genie')
    op.create_index(op.f('ix_genie_generated_files_user_id'), 'generated_files', ['user_id'], unique=False, schema='genie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genie_generated_files_user_id'), table_name='generated_files', schema='genie')
    op.drop_index(op.f('ix_genie_generated_files_conversation_id'), table_name='generated_files', schema='genie')
    op.drop_table('generated_files', schema='genie')
    # ### end Alembic commands ###
